package models

import "errors"

var (
	ErrUserNotFound             = errors.New("User not found")
	ErrRoleNotFound             = errors.New("Role not found")
	ErrTripNotFound             = errors.New("Business trip not found")
	ErrDepartmentNotFound       = errors.New("Department not found")
	ErrTokenNotFound            = errors.New("Token not found")
	ErrUserAlreadyExists        = errors.New("User already exists")
	ErrRoleAlreadyExists        = errors.New("Role already exists")
	ErrDepartmentAlreadyExists  = errors.New("Department already exists")
	ErrTokenAlreadyBlacklisted  = errors.New("Token already blacklisted")
	ErrUnauthorizedAccess       = errors.New("Unauthorized access")
	ErrTokenInvalid             = errors.New("Token tidak valid")
	ErrTokenRevoked             = errors.New("Token sudah tidak berlaku")
	ErrTokenVerificationFailed  = errors.New("Gagal memverifikasi token")
	ErrRoleContextMissing       = errors.New("Akses ditolak: Sesi tidak memiliki data peran")
	ErrRoleForbidden            = errors.New("Akses ditolak: Peran Anda tidak memiliki otoritas")
	ErrInvalidStatus            = errors.New("Invalid status")
	ErrUserDeleted              = errors.New("User has been deleted")
	ErrEmailAlreadyExists       = errors.New("Email sudah terdaftar, silakan gunakan email lain")
	ErrEmailNotRegistered       = errors.New("Email tidak terdaftar")
	ErrInvalidPassword          = errors.New("Password salah")
	ErrTokenRequired            = errors.New("Token tidak boleh kosong")
	ErrSuperAdminOnly           = errors.New("Hanya super admin yang dapat melakukan operasi ini")
	ErrDepartmentInputRequired  = errors.New("Nama dan kode departemen tidak boleh kosong")
	ErrDepartmentUpdateRequired = errors.New("Setidaknya nama atau kode departemen harus diisi")
	ErrDepartmentIDInvalid      = errors.New("ID departemen tidak valid")
	ErrRoleNameRequired         = errors.New("Nama role tidak boleh kosong")
	ErrRoleNameExists           = errors.New("Role dengan nama tersebut sudah ada")
	ErrRoleIDInvalid            = errors.New("ID role tidak valid")
	ErrUserIDInvalid            = errors.New("ID pengguna tidak valid")
	ErrTripIDInvalid            = errors.New("ID perjalanan dinas tidak valid")
	ErrUserNotFoundMessage      = errors.New("Pengguna tidak ditemukan")
	ErrTripAccessDenied         = errors.New("Akses ditolak: Anda tidak memiliki akses untuk mengubah data ini")
	ErrTripDeleteAccessDenied   = errors.New("Akses ditolak: Anda tidak memiliki akses untuk menghapus data ini")
	ErrTripViewAccessDenied     = errors.New("Akses ditolak: Anda hanya dapat melihat data perjalanan dinas dari departemen Anda")
	ErrTripStatusAccessDenied   = errors.New("Akses ditolak: Anda hanya dapat mengubah status perjalanan dinas dari departemen Anda")
	ErrTripDateInvalidStart     = errors.New("Format tanggal mulai tidak valid, gunakan YYYY-MM-DD")
	ErrTripDateInvalidEnd       = errors.New("Format tanggal selesai tidak valid, gunakan YYYY-MM-DD")
	ErrTripDateRangeInvalid     = errors.New("Tanggal selesai tidak boleh sebelum tanggal mulai")
	ErrTripAttachmentRequired   = errors.New("Minimal satu file lampiran diperlukan")
	ErrTripAttachmentTooLarge   = errors.New("File melebihi batas maksimal ukuran 5MB")
	ErrTripAttachmentExtension  = errors.New("format file harus pdf")
	ErrTripAttachmentOpen       = errors.New("Gagal membuka file lampiran")
	ErrTripAttachmentRead       = errors.New("Gagal membaca file lampiran")
	ErrTripAttachmentSave       = errors.New("Gagal menyimpan file lampiran")
)
